TRATAMIENTO DE DATOS

In [1]:
import pandas as pd
#cargando el archivo y mostrando cicno filas
df_original = pd.read_csv("base_ventas.csv", sep=";")
df_original.head()

,matricula_funcionario,Nombre Funcionario,Cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,Categoria,precio_costo,valor_unitario,cantidad,comision,dt_venta,dt_entrega
0,123456111,José María,Vendedor,CL001,Tienda Matriz,10013,Fogón,Electrodomésticos,"210,9","404,1",1,NaN,28/09/20 16:19,5/10/20 16:31
1,123456111,José María,Vendedor,CL001,Tienda Matriz,10018,Colchón,Casa,"109,9","249,9",1,NaN,7/03/20 12:47,8/03/20 12:47
2,123456111,José María,Vendedor,CL001,Tienda Matriz,10014,Heladera,Electrodomésticos,"699,9","1346,9",1,NaN,21/04/19 10:48,23/04/19 15:55
3,123456111,José María,Vendedor,CL001,Tienda Matriz,10001,Smartphone,Electrónicos,"899,9","1676,9",1,NaN,7/05/20 17:59,8/05/20 14:31
4,123456111,José María,Vendedor,CL001,Tienda Matriz,10004,Máquina de lavar ropa,Electrodomésticos,1099,"1709,1",1,"0,05",14/08/19 16:56,19/08/19 15:52

In [2]:
#duplicando el dataframe
df = df_original.copy()

In [3]:
#cambiando el nombre de las columnas mpara estandarizar el nombre de las mismas (mayusculas primero y luegoi minusculas)
#imprimiendo los nombres originales
df.columns
#copiamos, estandarizamos y la modificacion la asignamos a una variable
nombre_columnas = ['matricula_funcionario', 'nombre_funcionario', 'cargo', 'codigo_tienda',
       'nombre_tienda', 'codigo_producto', 'descripcion_producto', 'categoria',
       'precio_costo', 'valor_unitario', 'cantidad', 'comision', 'dt_venta',
       'dt_entrega']

#cambiamos el nombre de las columnas con las nuevas
df.columns = nombre_columnas
#verificamos que se haya hecho el cambio
df.head()

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,comision,dt_venta,dt_entrega
0,123456111,José María,Vendedor,CL001,Tienda Matriz,10013,Fogón,Electrodomésticos,"210,9","404,1",1,NaN,28/09/20 16:19,5/10/20 16:31
1,123456111,José María,Vendedor,CL001,Tienda Matriz,10018,Colchón,Casa,"109,9","249,9",1,NaN,7/03/20 12:47,8/03/20 12:47
2,123456111,José María,Vendedor,CL001,Tienda Matriz,10014,Heladera,Electrodomésticos,"699,9","1346,9",1,NaN,21/04/19 10:48,23/04/19 15:55
3,123456111,José María,Vendedor,CL001,Tienda Matriz,10001,Smartphone,Electrónicos,"899,9","1676,9",1,NaN,7/05/20 17:59,8/05/20 14:31
4,123456111,José María,Vendedor,CL001,Tienda Matriz,10004,Máquina de lavar ropa,Electrodomésticos,1099,"1709,1",1,"0,05",14/08/19 16:56,19/08/19 15:52

CAMBIANDO EL TIPO DE DATO

In [4]:
#analizamos el tipo de dato de todas las columnas
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   int64
 1   nombre_funcionario     3000 non-null   object
 2   cargo                  3000 non-null   object
 3   codigo_tienda          3000 non-null   object
 4   nombre_tienda          3000 non-null   object
 5   codigo_producto        3000 non-null   int64
 6   descripcion_producto   3000 non-null   object
 7   categoria              3000 non-null   object
 8   precio_costo           3000 non-null   object
 9   valor_unitario         3000 non-null   object
 10  cantidad               3000 non-null   int64
 11  comision               159 non-null    object
 12  dt_venta               3000 non-null   object
 13  dt_entrega             3000 non-null   object
dtypes: int64(3), object(11)
memory usage: 328.3+ KB

In [5]:
#asi se cambia el tipo de dato
df["matricula_funcionario"] = df["matricula_funcionario"].astype("str")
#o tambien así
df = df.astype({
    "codigo_producto": "str"
})

In [6]:
#en el df hay columnas que tienen comas como separador decimal y eso no está bien, ya que se necesitan hacer calculos con las columnas hay que reemplazar las comas por puntos
df["precio_costo"] = df["precio_costo"].str.replace(",",".")
df["valor_unitario"] = df["valor_unitario"].str.replace(",",".")

In [7]:
#convertimos a float para manejar decimales
df = df.astype({
    "precio_costo": "float",
    "valor_unitario": "float"
})

#verificamos que se haya hecho el cambio}
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   object
 1   nombre_funcionario     3000 non-null   object
 2   cargo                  3000 non-null   object
 3   codigo_tienda          3000 non-null   object
 4   nombre_tienda          3000 non-null   object
 5   codigo_producto        3000 non-null   object
 6   descripcion_producto   3000 non-null   object
 7   categoria              3000 non-null   object
 8   precio_costo           3000 non-null   float64
 9   valor_unitario         3000 non-null   float64
 10  cantidad               3000 non-null   int64
 11  comision               159 non-null    object
 12  dt_venta               3000 non-null   object
 13  dt_entrega             3000 non-null   object
dtypes: float64(2), int64(1), object(11)
memory usage: 328.3+ KB

In [8]:
#cambiando la fecha a tipo date
df["dt_venta"] = pd.to_datetime(df["dt_venta"], format="%d/%m/%y %H:%M")
df["dt_entrega"] = pd.to_datetime(df["dt_entrega"], format="%d/%m/%y %H:%M")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   object
 1   nombre_funcionario     3000 non-null   object
 2   cargo                  3000 non-null   object
 3   codigo_tienda          3000 non-null   object
 4   nombre_tienda          3000 non-null   object
 5   codigo_producto        3000 non-null   object
 6   descripcion_producto   3000 non-null   object
 7   categoria              3000 non-null   object
 8   precio_costo           3000 non-null   float64
 9   valor_unitario         3000 non-null   float64
 10  cantidad               3000 non-null   int64
 11  comision               159 non-null    object
 12  dt_venta               3000 non-null   datetime64[ns]
 13  dt_entrega             3000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(1), object(9)
memory usage: 328.3+ KB

In [9]:
#consultando partes de la fecha
df["dt_entrega"].dt.year
df["dt_entrega"].dt.month
df["dt_entrega"].dt.hour

0       16
1       12
2       15
3       14
4       15
        ..
2995    10
2996    10
2997    14
2998    10
2999    17
Name: dt_entrega, Length: 3000, dtype: int32

TRTANDO DATOS FALTANTES

In [10]:
#mostrando las columnas que tienen valores faltantes
df.isna().sum()

matricula_funcionario       0
nombre_funcionario          0
cargo                       0
codigo_tienda               0
nombre_tienda               0
codigo_producto             0
descripcion_producto        0
categoria                   0
precio_costo                0
valor_unitario              0
cantidad                    0
comision                 2841
dt_venta                    0
dt_entrega                  0
dtype: int64

In [11]:
#rellenando los valores faltantes
df.fillna(0).head()
#se recomienda hacerlo asi: df["columna donde hay valores faltantes"].fillna(0) para que solo afecte esa columna
#y con este df["columna donde hay valores faltantes"] = df["columna donde hay valores faltantes"].fillna(0) se hace el cambio definitivo

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,comision,dt_venta,dt_entrega
0,123456111,José María,Vendedor,CL001,Tienda Matriz,10013,Fogón,Electrodomésticos,210.9,404.1,1,0,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José María,Vendedor,CL001,Tienda Matriz,10018,Colchón,Casa,109.9,249.9,1,0,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José María,Vendedor,CL001,Tienda Matriz,10014,Heladera,Electrodomésticos,699.9,1346.9,1,0,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José María,Vendedor,CL001,Tienda Matriz,10001,Smartphone,Electrónicos,899.9,1676.9,1,0,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José María,Vendedor,CL001,Tienda Matriz,10004,Máquina de lavar ropa,Electrodomésticos,1099.0,1709.1,1,"0,05",2019-08-14 16:56:00,2019-08-19 15:52:00

In [12]:
#metodo ffill()
df["comision"].ffill()

0        NaN
1        NaN
2        NaN
3        NaN
4       0,05
        ...
2995    0,09
2996    0,09
2997    0,09
2998    0,09
2999    0,09
Name: comision, Length: 3000, dtype: object

In [13]:
#metodo bfill()
df["comision"].bfill()

0       0,05
1       0,05
2       0,05
3       0,05
4       0,05
        ...
2995    0,09
2996    0,09
2997    0,09
2998    0,09
2999    0,09
Name: comision, Length: 3000, dtype: object

ELIMINANDO Y AGREGANDO COLUMNAS

In [14]:
#eliminado una columna
df.drop(columns=["comision"])
#eliminado una columna de forma definitiva
#df.drop(columns=["comision"], inplace=True)

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,dt_venta,dt_entrega
0,123456111,José María,Vendedor,CL001,Tienda Matriz,10013,Fogón,Electrodomésticos,210.9,404.1,1,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José María,Vendedor,CL001,Tienda Matriz,10018,Colchón,Casa,109.9,249.9,1,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José María,Vendedor,CL001,Tienda Matriz,10014,Heladera,Electrodomésticos,699.9,1346.9,1,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José María,Vendedor,CL001,Tienda Matriz,10001,Smartphone,Electrónicos,899.9,1676.9,1,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José María,Vendedor,CL001,Tienda Matriz,10004,Máquina de lavar ropa,Electrodomésticos,1099.0,1709.1,1,2019-08-14 16:56:00,2019-08-19 15:52:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspiradora de piso,Casa,88.9,189.9,3,2019-11-04 15:40:00,2019-11-05 10:40:00
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Licuadora,Cocina,59.9,142.4,3,2019-06-24 09:04:00,2019-06-24 10:50:00
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batidora,Cocina,49.9,95.9,3,2020-08-08 14:46:00,2020-08-09 14:07:00
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Freidora eléctrica,Cocina,187.9,340.0,3,2019-12-19 09:21:00,2019-12-19 10:51:00
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina de lavar ropa,Electrodomésticos,1099.0,1709.1,3,2019-03-18 15:40:00,2019-03-23 17:52:00

In [15]:
#Ceando columnas calculadas
df["valor_total"] = df["valor_unitario"] * df["cantidad"]

df.head()

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,comision,dt_venta,dt_entrega,valor_total
0,123456111,José María,Vendedor,CL001,Tienda Matriz,10013,Fogón,Electrodomésticos,210.9,404.1,1,NaN,2020-09-28 16:19:00,2020-10-05 16:31:00,404.1
1,123456111,José María,Vendedor,CL001,Tienda Matriz,10018,Colchón,Casa,109.9,249.9,1,NaN,2020-03-07 12:47:00,2020-03-08 12:47:00,249.9
2,123456111,José María,Vendedor,CL001,Tienda Matriz,10014,Heladera,Electrodomésticos,699.9,1346.9,1,NaN,2019-04-21 10:48:00,2019-04-23 15:55:00,1346.9
3,123456111,José María,Vendedor,CL001,Tienda Matriz,10001,Smartphone,Electrónicos,899.9,1676.9,1,NaN,2020-05-07 17:59:00,2020-05-08 14:31:00,1676.9
4,123456111,José María,Vendedor,CL001,Tienda Matriz,10004,Máquina de lavar ropa,Electrodomésticos,1099.0,1709.1,1,"0,05",2019-08-14 16:56:00,2019-08-19 15:52:00,1709.1

Ordenando el dataframe

In [16]:
#para ordenar una sola comumna
df.sort_values("descripcion_producto", ascending=True)
#para ordenar dos o mas columnas. El inplace es para hacer el cambio permanente
#df.sort_values(["descripcion_producto", "nombre_tienda"], ascending=[True, True], inplace=True)

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,comision,dt_venta,dt_entrega,valor_total
2806,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspiradora de piso,Casa,88.9,189.90,4,NaN,2020-03-08 16:03:00,2020-03-09 09:53:00,759.60
2172,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10006,Aspiradora de piso,Casa,88.9,189.90,2,NaN,2019-12-24 13:36:00,2019-12-24 17:43:00,379.80
397,123456222,Maria das Gra√ßas,Vendedor,CL001,Tienda Matriz,10006,Aspiradora de piso,Casa,88.9,189.90,2,NaN,2019-05-11 12:27:00,2019-05-12 10:34:00,379.80
2749,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspiradora de piso,Casa,88.9,189.90,2,NaN,2019-07-21 16:32:00,2019-07-21 17:45:00,379.80
1361,123456666,Reinaldo Salcedo,Vendedor,CL002,Filial MG,10006,Aspiradora de piso,Casa,88.9,189.90,4,NaN,2019-11-01 15:57:00,2019-11-01 16:03:00,759.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2873,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10003,Televisor,Electrodomésticos,1400.9,2279.99,1,NaN,2019-03-24 12:08:00,2019-03-27 14:42:00,2279.99
1796,123456999,Felipe Mariño,Vendedor,CL003,Filial SP,10003,Televisor,Electrodomésticos,1400.9,2279.99,3,NaN,2020-04-17 12:28:00,2020-04-23 13:59:00,6839.97
443,123456222,Maria das Gra√ßas,Vendedor,CL001,Tienda Matriz,10003,Televisor,Electrodomésticos,1400.9,2279.99,1,NaN,2019-09-12 12:38:00,2019-09-18 16:09:00,2279.99
2370,123457112,Mario Enrique,Vendedor,CL004,Filial ES,10003,Televisor,Electrodomésticos,1400.9,2279.99,4,NaN,2020-12-28 09:42:00,2020-12-31 09:04:00,9119.96
2428,123457112,Mario Enrique,Vendedor,CL004,Filial ES,10003,Televisor,Electrodomésticos,1400.9,2279.99,3,NaN,2020-04-07 17:29:00,2020-04-11 09:28:00,6839.97

In [17]:
#haciendo un reset del index. El drop significa que va a eliminar la columna vieja del indice
df.reset_index(drop=True)
#df.reset_index(drop=True, inplace=True) para hacer el cambio permanente

,matricula_funcionario,nombre_funcionario,cargo,codigo_tienda,nombre_tienda,codigo_producto,descripcion_producto,categoria,precio_costo,valor_unitario,cantidad,comision,dt_venta,dt_entrega,valor_total
0,123456111,José María,Vendedor,CL001,Tienda Matriz,10013,Fogón,Electrodomésticos,210.9,404.1,1,NaN,2020-09-28 16:19:00,2020-10-05 16:31:00,404.1
1,123456111,José María,Vendedor,CL001,Tienda Matriz,10018,Colchón,Casa,109.9,249.9,1,NaN,2020-03-07 12:47:00,2020-03-08 12:47:00,249.9
2,123456111,José María,Vendedor,CL001,Tienda Matriz,10014,Heladera,Electrodomésticos,699.9,1346.9,1,NaN,2019-04-21 10:48:00,2019-04-23 15:55:00,1346.9
3,123456111,José María,Vendedor,CL001,Tienda Matriz,10001,Smartphone,Electrónicos,899.9,1676.9,1,NaN,2020-05-07 17:59:00,2020-05-08 14:31:00,1676.9
4,123456111,José María,Vendedor,CL001,Tienda Matriz,10004,Máquina de lavar ropa,Electrodomésticos,1099.0,1709.1,1,"0,05",2019-08-14 16:56:00,2019-08-19 15:52:00,1709.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspiradora de piso,Casa,88.9,189.9,3,NaN,2019-11-04 15:40:00,2019-11-05 10:40:00,569.7
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Licuadora,Cocina,59.9,142.4,3,NaN,2019-06-24 09:04:00,2019-06-24 10:50:00,427.2
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batidora,Cocina,49.9,95.9,3,NaN,2020-08-08 14:46:00,2020-08-09 14:07:00,287.7
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Freidora eléctrica,Cocina,187.9,340.0,3,NaN,2019-12-19 09:21:00,2019-12-19 10:51:00,1020.0
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina de lavar ropa,Electrodomésticos,1099.0,1709.1,3,"0,09",2019-03-18 15:40:00,2019-03-23 17:52:00,5127.3

In [18]:
#cambiar la columna que fungirá como indice. inplace es para haecr los cambios permanentes
df.set_index("dt_venta", inplace=True)

EXPORTANDO UN NUEVO DATASET

In [19]:
#xportando a csv
df.to_csv("ventas_nuevo.csv")

#para que no exporte el index de pandas
df.to_csv("ventas_nuevo.csv", index=False)